name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  call-release-workflow:
    uses: ASFHyP3/actions/.github/workflows/reusable-release.yml@main
    with:
      release_prefix: {{ cookiecutter.project_title }}
    secrets:
      USER_TOKEN: {{'${{ secrets.TOOLS_BOT_PAK }}'}}
