name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  call-release-workflow:
    uses: ASFHyP3/actions/.github/workflows/reusable-release.yml@v0.7.0
    with:
      release_prefix: HyP3-CI
      release_branch: main
      develop_branch: develop
      sync_pr_label: actions-bot
    secrets:
      USER_TOKEN: ${{ secrets.GITHUB_USER_TOKEN }}
