name: Static analysis

on: push

jobs:
  call-secrets-analysis-workflow:
    uses: ASFHyP3/actions/.github/workflows/reusable-secrets-analysis.yml@v0.7.0

  call-flake8-workflow:
    uses: ASFHyP3/actions/.github/workflows/reusable-flake8.yml@v0.7.0
    with:
      #FIXME make package name
      local_package_names: hyp3_plugin  # Required; comma-seperated list of names that should be considered local to your application
      # excludes: hyp3_plugin/ugly.py   # Optional; comma-separated list of glob patterns to exclude from checks
