name: Tag New Version

on:
  push:
    branches:
      - main

jobs:
  call-bump-version-workflow:
    uses: ASFHyP3/actions/.github/workflows/reusable-bump-version.yml@v0.7.0
    with:
      user: {{ cookiecutter.github_username }}
      email: {{ cookiecutter.github_email }}
    secrets:
      USER_TOKEN: {{'${{ secrets.GITHUB_PAK }}'}}
